# Site settings
title: "vancexu's bolg"
slogan: "not now, when?"
email: xuboweinju@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal bolg of Bowei Xu (vancexu). 
  Share about information technologies, self improvement, open courses and books. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vancexu.github.com" # the base hostname & protocol for your site
twitter_username: vancexu
github_username:  vancexu

# Build settings
markdown: kramdown

gems: 
  - jemoji

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      is_post: true
      author: vancexu

# Markdown settings
kramdown:
  input: GFM
